name: Daily Telegram Bot

on:
  schedule:
    - cron: '30 3 * * *'  # 9:00 AM IST
  workflow_dispatch:     # manual run option bhi milega

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: node index.js
